apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-helm
spec:
  template:
    spec:
      containers:
        - name: helm-app
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
